### ISSUE TITLE
Create Detailed Hacktoberfest Readme

### ISSUE THREAD

**Issue by vrittles** [vrittles/Mini-Projects#2]
Create Detailed Hacktoberfest Readme for this Repository including the rules.
Also add directions to fork and star this repository.

**Comment by Arcturus22** [comment]
Assign me this issue please
@SanghiNinja

**Comment by SanghiNinja** [comment]
Sure

**Comment by Arcturus22** [comment]
@SanghiNinja 
Just want to confirm before adding to the README file, this repo is for adding small-projects web/ app development-based projects, right?
Please clarify what this repository is about so I can add more in the README markdown

**Comment by SanghiNinja** [comment]
Yes, this repo is for mini javascript projects

**Comment by anshul-132002** [comment]
@vrittles i want to contribute to this issue

**Comment by vrittles** [comment]
> @vrittles i want to contribute to this issue

okay, the readme is already there... lets see if u can make it better

**Comment by anshul-132002** [comment]
> > @vrittles i want to contribute to this issue
> 
> okay, the readme is already there... lets see if u can make it better

Assign me !

**Comment by vrittles** [comment]
lmao sorry forgot to assign
